### ISSUE TITLE
Using wiresham to mock http request/response

### ISSUE THREAD

**Issue by yuriylesyuk** [abstracta/wiresham#12]
Is it possible to use wiresham with curl or other http client to mock http traffic?

I captured some http requests and responces. 

Started wiresham. the -vv option gives me some glimpse under the hood.

When I am sending a curl request identical to the captured, I can see in the log following output but curl just keep waiting:
```

19:44:08.464 [pool-2-thread-1] INFO us.abstracta.wiresham.ClientConnection - starting new flow ...
19:44:08.464 [pool-2-thread-1] DEBUG us.abstracta.wiresham.ClientPacketStep - Waiting for 474554202F72...2F2A0D0A0D0A
19:44:08.464 [pool-2-thread-1] TRACE us.abstracta.wiresham.ClientConnection - reading from socket
19:44:08.465 [pool-2-thread-1] TRACE us.abstracta.wiresham.ClientConnection - read from socket: 474554202F72...2A2F2A0D0A0D0A
19:44:08.465 [pool-2-thread-1] TRACE us.abstracta.wiresham.ClientPacketStep - Searching for 474554202F72...3A202A2F2A0D0A0D0A from 0
19:44:08.465 [pool-2-thread-1] TRACE us.abstracta.wiresham.ClientPacketStep - Start match at 0
19:44:08.465 [pool-2-thread-1] DEBUG us.abstracta.wiresham.ClientPacketStep - received expected 474554202F7...02A2F2A0D0A0D0A
19:44:08.465 [pool-2-thread-1] DEBUG us.abstracta.wiresham.ClientPacketStep - Waiting for 485454502F312E3120...3656432336631227D7D7D0D0A300D0A0D0A
19:44:08.465 [pool-2-thread-1] TRACE us.abstracta.wiresham.ClientConnection - reading from socket
<both curl and wiresham waits indefinately>

```

Effectively, the mock server read and identified an expected request, but then instead of serving this request response it is _waiting_ for it: 'Waiting for...' is the hex sequence for the http response.

**Comment by rabelenda** [comment]
Thank you for trying Wiresham and asking the question!

Keep in mind that wiresham is very limited (as stated in [Readme](https://github.com/abstracta/wiresham)) since is TCP based and very simple, and will only answer if the provided bytes sequence are exactly the same as the ones in the captured dump. So if anything changes between curl requests, then wiresham will not know how to answer. For HTTP based traffic prefer [WireMock](http://wiremock.org/) or [mountebank](http://www.mbtest.org/).

Regards
