### ISSUE TITLE
Wiresham 0.6 artifact to maven central

### ISSUE THREAD

**Issue by gvagenas** [abstracta/wiresham#13]
Wiresham 0.6 is not available in the maven central

**Comment by rabelenda** [comment]
Thank you for reporting this, and sorry for the inconvenience.

The pipeline that uploads the artifact to maven has been failing due to maven central timeouts during release. We have requested and just updated the pipeline to use an alternative server provided by maven team.

The release now succeeded and the artifact should appear soon in maven central (after it refreshes it's cache).

Regards.

**Comment by gvagenas** [comment]
Thanks @rabelenda
