### ISSUE TITLE
Documentation on how to use wiresham with practical examples.

### ISSUE THREAD

**Issue by droidtrail** [abstracta/wiresham#3]
Hello. I'm wondering how to use WireSham to do TCP Mocking. Reading the documentation in GitHub, I realized that the tool does not have a graphical interface, but a framework written in java that should be low and executed, for example, using the Eclipse IDE. Is that right?
If so, do you have any documentation that you can provide with the step-by-step guide on how to use WireSham?
If yes, please send them to my email: leandro.nares@gmail.com.

**Comment by rabelenda** [comment]
Hello, as you have noted Wiresham has no UI yet. The basic usage of the tool is described in the readme, you basically capture traffic between a client application and server application that you want to mock with Wireshark or Tcpdump, save the traffic dump, and then load it in Wiresham to emulate the server application. 
Additionally, you can convert Wireshark and Tcpdump traffic dumps to a simplified version (a yaml file) with Wiresham, and use that in Wiresham instead of a traffic dump to configure the server mock.  You can also manually create such yaml, but that would require knowing exactly the expected bytes from client application and server application which would be tricky, but you can get a converted dump (from Wireshark or Tcpdump) and modify it to test other things that are not contemplated in original traffic dump.
Regarding the "Java framework" that you mention, is just a small API which allows you to configure a mock server with a given dump and start/stop the server, which is really simple but useful when developing test to validate some client logic (with for example JUnit). Such tests may be implemented with Eclipse IDE or any other IDE or text editor.

Regarding step by step guid, there is the readme, and we have also demoed its usage in a webinar (to mock mainframe applications, but mainframe applications are just one kind of TCP app). You can find it here: https://youtu.be/Sr1BOi50xqg?t=2036. Wiresham is presented from minute 33 until minute 45.

If you have any further questions don't hesitate on asking them via this medium, and add a start to the project if you find it helpful :-)

**Comment by droidtrail** [comment]
Thanks for the reply, rabelenda. I'll check the YouTube video on to try to understand better how the tool works.

**Comment by AhmedAljailani** [comment]
where is the practical example

**Comment by rabelenda** [comment]
@AhmedAljailani Have you checked the video I shared with @droidtrail in previous comment? We plan on adding a small gif/video in repo readme for reference in the near future.

**Comment by AhmedAljailani** [comment]
> 
> 
> @AhmedAljailani Have you checked the video I shared with @droidtrail in previous comment? We plan on adding a small gif/video in repo readme for reference in the near future.

could you send it to me

**Comment by rabelenda** [comment]
It's in [this same issue](https://github.com/abstracta/wiresham/issues/3#issuecomment-451529421), the youtube video from the point wiresham is presented: https://youtu.be/Sr1BOi50xqg?t=2036
