### ISSUE TITLE
A way to verify if VirtualTcpService was called

### ISSUE THREAD

**Issue by mdanetzky** [abstracta/wiresham#4]
Hi, thanks for a great library! I'm looking for a functionality, that will tell me if my VirtualTcpService instance has received any request. Preferably even a way to see what was called and how many times. Do you have an idea how to approach this task using WireSham?

**Comment by rabelenda** [comment]
Hello, the library provides extensive logging when log level is set to trace providing information on all received bytes. I guess anyways that you mean a programmatic way to check and retrieve information. The main way the library has to identify if the expected bytes were received is just checking that you get the expected response from the library/mock according to what you define in the dump. Can you clarify further your need? Maybe provide some pseudo code to better answer your question?

**Comment by mdanetzky** [comment]
I need to test a balancer service. I start two instances of wiresham, fire up the balancer and now I need to assert/verify, that both instances were called.

**Comment by rabelenda** [comment]
What about using slightly different dumps in each of the instances and verify from client code that you are getting the right proportion of them? 

Regarding wiresham, since state of connection is lost after each connection is closed, we would need to implement some management API (both programmatic and through REST API additional port in case it is used in standalone mode) to allow querying for such information which could be just getting the number of connections established to the service, or could also be in the way of getting some connections state changes logs through the api (implementing some configurable limit to avoid running out of RAM). 

Is the load balancer an HTTP based load balancer? if so, have you considered using wiremock which already provides some management API and logging?

Regarding potential ideas for management api, it could be a `ServerStats VirtualTcpService.getStats()` method with `ServerStats(int totalClientConnectionsCount)` and the associated rest endpoint (`GET /stats` with response like `{"totalClientConnectionsCount": 5}`, and for logs could be something like `List<FlowStepTransition> VirtualTcpService.getFlowStepTransitions()` with `FlowStepTransition(int connectionId, String toStepId)` (Using string in stepId instead of int since we plan to have non linear flows in near future) with associated rest endpoint (`GET /transitions` `[{"connectionId": 4, "toStepId": "3"}]` and associated new properties for setup of management (with default values): maxTransitionsHistoryCount & managementApiPort.

Does this align with your need? Any thoughts?

You are more than welcome to implement any of the two above management endpoints if they align with your need, and submit a pull request if you can.

Thank you for letting us know of your particular needs and contributing to the project.

**Comment by rabelenda** [comment]
Hi, any comments?

**Comment by mdanetzky** [comment]
Hi,
I had to change a lot of code to accommodate out of order request-response logic. This means, that the process of reviewing and changing it would be very long and complicated, for which I don't have time at the moment. So feel free to do your changes and I will simply publish mine in my fork for the time being. Let's decide later what would be the best course of action.
